project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "BlogMatsumoto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/IsabellaMatsumoto
      - icon: linkedin
        href: https://www.linkedin.com/in/isabella-matsumoto/
format:
  html:
    theme:
      - flatly
      - lux
    css: styles.css



